# Spring properties
spring:
  application:
     name: messages

# Discovery Server Access
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/


# HTTP Server
server:
  port: 2222   # HTTP (