# Spring properties
spring:
  application:
     name: messages

# Discovery Server Access
eureka:
  instance:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/


# HTTP Server
server:
  port: 2222   # HTTP (