# Configure this Discovery Server
eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    enableSelfPreservation: true

spring:
      application:
              name: registration

server:
  port: 1111   # HTTP (Tomcat)